### ISSUE TITLE
Enhancing with futur pull request

### ISSUE THREAD

**Issue by ClementJ35** [thorian93/ansible-role-common-proxy#1]
Hi,
I'm interested by this role.
But I need to enhance it for 3 things : 

- [x]  Handle different proxy for package-managers and other proxies ( in order to use apt-cacher-ng )
- [x]  Handle yum / dnf package manager
- [x]  Handle systemd system var

Would you accept pull request on those evolution ?

Regards,
Clément

**Comment by ClementJ35** [comment]
First Pull Request #2

**Comment by thorian93** [comment]
I am just finishing up my refinements and cleanups from your PRs. Will update here once that's done.

**Comment by thorian93** [comment]
Just released version `0.2.0` of the role. :rocket: 
Take a look if I did not break anything for you and let me know what you think.

**Comment by ClementJ35** [comment]
I'll test it these days, but that seems good to me.
Just one thing, dnf_yum switch is missing from the readme.md ( I added it outside the branch, my bad ).

**Comment by thorian93** [comment]
Alright great. I fixed the README in 91679417a562037e308cadd4b37de09e6bed6371.

I'll keep this issue open in case there something left to discuss. Feel free to close if you are happy with the results.

**Comment by ClementJ35** [comment]
:+1: I'm actually happy :-)
Let's close this.
