### ISSUE TITLE
why webserver as dependency ?

### ISSUE THREAD

**Issue by ClementJ35** [thorian93/ansible-role-common-proxy#8]
Hi,

You introduce your webserver role as dependency. Why is that ?
It is not required at all.

**Comment by thorian93** [comment]
See https://github.com/thorian93/ansible-role-common-proxy/blob/master/tasks/apache2.yml line 4.

This strategy is debatable and again feel free to keep your fork and change this. But I am using this as my standard to handle web servers (apache2, httpd, NGINX) automatically, without the need to hardwire variables to either of those daemons and paths.

**Comment by ClementJ35** [comment]
Hi,
I'll go for a fork because I want to keep it KISS, but it feels bad not to aggregate the efforts.

Have fun.

**Comment by thorian93** [comment]
Sure thing, feel free.

I appreciate every pull request with general improvements, if you like.

Take care!
